#!/usr/bin/env ruby

require 'fileutils'
require 'erb'
require 'rake'
require 'active_support/core_ext/object'
require 'slatan/utils/string_ex'

using Slatan::Utils::StringEx

def generate(path)
  if path.nil?
    puts 'Usage: slatan generate </path/to/your/preference/subscriber/name>' 
    exit 0
  end

  file_name = File.basename(path, '.*')
  class_name = file_name.camelize
  dir_path = File.dirname(path)
  FileUtils.mkdir_p dir_path
  File.open(File.expand_path('../../lib/slatan/template/concern.rb.erb', __FILE__)) do |file|
    erb = ERB.new(file.read).result(binding)
    File.open(File.join(dir_path, "#{file_name}.rb"), 'w') do |file|
      file << erb
    end
  end
  puts 'generated.'
end

def kill
  pid_file_path = ENV['SLATAN_PID_FILE_PATH'].presence || '/tmp/slatan.pid'
  if !FileTest.exist? pid_file_path
    puts "'#{pid_file_path}' is not exist."
    exit 0
  end
  sh "kill `cat #{pid_file_path}`"
  puts 'killed.'
end

if $*[0] == 'generate'
  generate($*[1])
elsif $*[0] == 'kill'
  kill
else 
  puts 'Usage: slatan <COMMAND>'
  puts '=======COMMAND========'
  puts 'generate </path/to/your/preference/subscriber/name>: Generate subscriber class file.' 
  puts 'kill: kill daemon process of slatan.' 
  exit 0
end

